apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: "publish test conversion"
inputs:
  test-type:
    description: 'Test Type indicating testing tool report that needs conversion'
    required: true

  folder-name:
    description: 'Folder name/File path for the location of the test reports'
    required: true
runs:
  using: composite
  steps:
    - id: publish-test-results
      name: publish test results
      uses: docker://public.ecr.aws/l7o7z1g8/actions/publish-test-results:main-ba15dc53f17467593fac5149df0111653ead6cab 
      # uses: docker://020229604682.dkr.ecr.us-east-1.amazonaws.com/actions/publish-test-results:main-ba15dc53f17467593fac5149df0111653ead6cab
      shell: sh
      env:
        CONFIG_JSON: '{"metaInfo":{"testType":"${{ inputs.test-type }}","folderName":"${{ inputs.folder-name }}"}}'
        RUN_ID: ${{ cloudbees.run_id }}
        JOB_ID: ${{ job.id }}
        STEP_ID: ${{ step.internal.id }}
        DNS_URL: ${{ cloudbees.api.url }}
        JWT_TOKEN: ${{ cloudbees.api.token }}
      run: |
        set -x
        cd /app
        ./publish_test_results invoke -i $CONFIG_JSON
