apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: publish test conversion

inputs:
  test-type:
    description: Test Type indicating testing tool report that needs conversion
    required: true
  folder-name:
    description: Folder name/File path for the location of the test reports
    required: true
    
runs:
  steps:
    - id: publish-test-results
      name: publish test results
      uses: docker://public.ecr.aws/l7o7z1g8/actions/publish-test-results:main-63e77572cd594e944ad308841b6b3a04c1421c9c
      env:
        CONFIG_JSON: '{"metaInfo":{"testType":"${{ inputs.test-type }}","folderName":"${{ inputs.folder-name }}"}}'
        RUN_ID: ${{ cloudbees.run_id }}
        JOB_ID: ${{ job.id }}
        STEP_ID: ${{ step.internal.id }}
        DNS_URL: ${{ cloudbees.api.url }}
        JWT_TOKEN: ${{ cloudbees.api.token }}
      run: /app/publish-test-results invoke -i $CONFIG_JSON
