apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: publish test conversion

inputs:
  test-type:
    description: Test Type indicating testing tool report that needs conversion
    required: true
  results-path:
    description: The pattern, file, or directory path of the test report to convert
    required: true
    
runs:
  steps:
    - id: publish-test-results
      name: publish test results
      uses: docker://public.ecr.aws/l7o7z1g8/actions/publish-test-results:main-123c4815be02451c966e1fd521b566576f6d2baa
      env:
        CONFIG_JSON: '{"metaInfo":{"testType":"${{ inputs.test-type }}","folderName":"${{ inputs.results-path }}"}}'
        RUN_ID: ${{ cloudbees.run_id }}
        JOB_ID: ${{ job.id }}
        STEP_ID: ${{ step.internal.id }}
        DNS_URL: ${{ cloudbees.api.url }}
        JWT_TOKEN: ${{ cloudbees.api.token }}
      run: /app/publish-test-results invoke -i $CONFIG_JSON
