= CloudBees action: Publish test results

Use this action to publish test results if you are using a CloudBees platform workflow.
This action supports many popular testing tools, and enables testing results from running a platform workflow to be displayed in the link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/workflows/test-results[Test results] tab of *Run details* and in the link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/analytics/test-insights[Test insights] analytics dashboard.

== Inputs

[cols="2a,1a,1a,3a",options="header"]
.Input details
|===

| Input name
| Data type
| Required
| Description

| `test-type`
| String
| Yes
| The name of the testing tool^[1]^.

| `folder-name`
| String
| Yes
| The pattern, file, or directory path of the test report to convert.

|===

^[1]^ The testing tool name must be formatted correctly, in either all lowercase, or all uppercase.

== Supported testing tools

NOTE: Only the testing tools listed in the table below are supported for use in this action.

Use the given `test-type` input format to specify a testing tool.

[cols="40%a,30%a,30%a"]
.Supported testing tool names and `test-type` format
|===
h| Supported tool name
2+h| Accepted `test-type` input formats

|
| lowercase
| UPPERCASE

| GO
| `go`
| `GO`

| Jest
| `jest`
| `JEST`

| JMeter
| `jmeter`
| `JMETER`

| JUnit
| `junit`
| `JUNIT`

| MSTest
| `mstest`
| `MSTEST`

| Playwright
| `playwright`
| `PLAYWRIGHT`

| ProdPerfect
| `prodperfect`
| `PRODPERFECT`

| Selenium
| `selenium`
| `SELENIUM`

| TestNG
| `testng`
| `TESTNG`

| Tosca
| `tosca`
| `TOSCA`

|===

== Usage example

In your YAML file, add:

[source,yaml]
----
    - name: Publish test results
      uses: https://github.com/cloudbees-io/publish-test-results@v1
      with:
        test-type: TESTNG
        folder-name: /example/mytest

----

== License

This code is made available under the 
link:https://opensource.org/license/mit/[MIT license].

== References

* Learn more about link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/actions[using actions in CloudBees workflows].
* Learn about link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/[the CloudBees platform].

