= CloudBees action: Publish test results

Use this action to publish test results if you are using a CloudBees platform workflow.
This action supports many popular testing tools, and enables testing results from running a platform workflow to be displayed in the link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/workflows/test-results[Test results] tab of *Run details* and in the link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/analytics/test-insights[Test insights] analytics dashboard.

== Inputs

[cols="2a,1a,1a,3a",options="header"]
.Input details
|===

| Input name
| Data type
| Required
| Description

| `test-type`
| String
| Yes
| The name of the testing tool^[1]^.

| `results-path`
| String
| Yes
| The pattern, file, or directory path of the test report to convert.

|===

^[1]^ The testing tool name must be formatted correctly, in either all lowercase, or all uppercase.

== Supported testing tools

NOTE: Only the testing tools listed in the table below are supported for use in this action.

Use the given `test-type` input format to specify a testing tool.

[cols="40%a,30%a,30%a"]
.Supported testing tool names and `test-type` format
|===
h| Supported tool name
2+h| Accepted `test-type` input formats

|
| lowercase
| UPPERCASE

| GO
| `go`
| `GO`

| Jest
| `jest`
| `JEST`

| JMeter
| `jmeter`
| `JMETER`

| JUnit
| `junit`
| `JUNIT`

| MSTest
| `mstest`
| `MSTEST`

| Playwright
| `playwright`
| `PLAYWRIGHT`

| ProdPerfect
| `prodperfect`
| `PRODPERFECT`

| Selenium
| `selenium`
| `SELENIUM`

| TestNG
| `testng`
| `TESTNG`

| Tosca
| `tosca`
| `TOSCA`

|===

== Usage examples

=== Basic example

The following is a basic example of using the action:

[source,yaml]
----
      - name: Publish test results
        uses: cloudbees-io/publish-test-results@v2
        with:
          test-type: TESTNG
          results-path: /example/mytest

----

=== Go test example

The following example specifies the GO testing tool.
To use this tool, capture the output into a log, and then convert the log into a JUnit test report.
Publish the results based on either:

* A JUnit `test.xml`.
* A JSON formatter.

[source,yaml]
----
    - name: Publish GO test results
      uses: cloudbees-io/publish-test-results@v2
      with:
        test-type: GO
        results-path: /example/myGOtest

----

##I am not sure how to document the GO test##
go test -v -timeout 15m -coverprofile $COVER -coverpkg "$PKGS_CSV" ./... | tee ./test.log
cat ./test.log | go-junit-report >./test.xml

=== Full workflow example

In the following example, source code from a repository is checked out in the CloudBees platform and tested with the Playwright tool.
After configuring AWS credentials, the test results are compressed and archived using Docker.
The test results are uploaded to an AWS S3 bucket and published as evidence in the platform.

.Example workflow YAML file
[.collapsible]
--

[source, yaml,role="default-expanded"]
----

apiVersion: automation.cloudbees.io/v1alpha1
name: trigger-publish-test-results-action
kind: workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  Playwright-Test:
    steps:
      - name: Check out source code
        uses: cloudbees-io/checkout@v1
        with:
          repository: my-name/my-repo-name

      - name: PlayWright test
        uses: cloudbees-io/publish-test-results@v2
        with:
          test-type: playwright
          folder-name: ${{ cloudbees.workspace }}/test_data/playwright/results_failed.json

      - name: Configure AWS credentials
        uses: cloudbees-io/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.MY_AWS_ID }}
          aws-secret-access-key: ${{ secrets.MY_AWS_SECRET_KEY }}

      - id: compress-and-archive-test-evidence
        name: Compress and archive test evidence
        uses: docker://golang:1.20-alpine
        shell: sh
        run: |
          mkdir -p ${{ cloudbees.workspace }}/test-data/playwright/test-results
          tar -czf ${{ cloudbees.workspace }}/test-data/playwright/test-results.tar.gz -C ${{ cloudbees.workspace }}/test-data/playwright/test-results .

      - name: S3 upload test evidence archive
        uses: cloudbees-io/s3-upload-object@v1
        with:
          file-path: ${{ cloudbees.workspace }}/test-data/playwright/test-results.tar.gz
          bucket-name: my-testing-logs
          s3-path: s3-folder/${{ cloudbees.run_id}}.tar.gz
          send-artifact-info: "true"

  Test-evidence:
      steps:
      - name: Publish evidence item
        uses: cloudbees-io/publish-evidence-item@v1
        with:
          content: |
            - Run ID: ${{ cloudbees.run_id }}
            - [backend.tar](https://ourcompany.com/repo/backend.tar)

----
--

== License

This code is made available under the 
link:https://opensource.org/license/mit/[MIT license].

== References

* Learn more about link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/actions[using actions in CloudBees workflows].
* Learn about link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/[the CloudBees platform].

